// Objective-C API for talking to hello Go package.
//   gobind -lang=objc hello
//
// File is generated by gobind. Do not edit.

#ifndef __Hello_H__
#define __Hello_H__

@import Foundation;
#include "Universe.objc.h"


@class HelloInput;
@class HelloOutput;
@protocol HelloEventListener;
@class HelloEventListener;

@protocol HelloEventListener <NSObject>
- (void)callback:(HelloOutput*)output;
@end

@interface HelloInput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)name;
- (void)setName:(NSString*)v;
@end

@interface HelloOutput : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)msg;
- (void)setMsg:(NSString*)v;
@end

FOUNDATION_EXPORT void HelloHello(HelloInput* input, id<HelloEventListener> listener);

@class HelloEventListener;

@interface HelloEventListener : NSObject <goSeqRefInterface, HelloEventListener> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)callback:(HelloOutput*)output;
@end

#endif
